LogTime yes
LogVerbose yes
Foreground yes
TCPSocket 3310
TCPAddr 0.0.0.0

# OJO: no uses LocalSocket aqu?; as? forzamos TCP
# LocalSocket /run/clamav/clamd.ctl

# (Opcional) si subes archivos grandes, levanta el l?mite del stream
# StreamMaxLength 200M